site_name: Ryan Muoio
site_url: https://Muoio117.github.io # https://ryanmuoio.com
docs_dir: docs  # Source files (index.md, etc.)
site_dir: site  # Output for mkdocs build (ignored by .gitignore)

theme:
  name: material
  font: 
    code: Red Hat Mono
  logo: assets/images/R.png
  favicon: assets/favicon.ico
  features:
    - navigation.footer
    - navigation.instant
    - navigation.instant.progress
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    #- navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - toc.integrate
    #- content.footnote.tooltips
  palette: 
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: blue grey
      accent: deep orange

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange

nav:
  #- Home: index.md
  - About: 
    - Me: about/introduction.md
  - Anim Tools:
    - Anim Tools: products/animtools.md
  - Animation Matching Suite:
    - Animation Matching Suite: products/animationmatchingsuite.md
    

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg  
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
            - name: mermaid
              class: mermaid
              format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - pymdownx.details
  - footnotes
  - md_in_html

extra: 
  generator: false
  social:
    - icon: simple/youtube
      link: https://www.youtube.com/@ryanmuoio6569
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/ryan-muoio/
    - icon: simple/x
      link: https://x.com/RyanMuoio
    - icon: simple/fab
      link: https://www.fab.com/sellers/MuuKnighted%20Games

extra_css:
  - stylesheets/custom.css

plugins:
  - search
  - tags

copyright: Copyright &copy; 2025 Ryan Muoio